
application:
  fs:
    path: "${HOME}/.kanban-hub"
# can be overwritten in a application-default.yml


# DataSource
spring:
  config:
    use-legacy-processing: true
    additional-location: "file:./config"
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: "jdbc:hsqldb:file:${application.fs.path}/db/kanban_hub"
    password:
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    change-log: "classpath:dbchangelog.xml"


