management:
  metrics:
    enable:
      all: false
      jvm: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
   #  base-path: /mgmt, to change from /actuator
  endpoint:
    health:
      show-details: "always"


# actuator endpoints
endpoints:
  prometheus:
    enabled: true
server:
  servlet:
    context-path: "/api"
