management:
  metrics:
    enable:
      all: false
      jvm: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"



endpoints:
  prometheus:
    enabled: true
server:
  servlet:
    context-path: "/api"
