
application:
  fs:
    path: "${HOME}/.kanban-hub"

# DataSource
spring:
  config:
    additional-location: "file:./config"
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: "jdbc:hsqldb:file:${application.fs.path}/var/kanban_hub"
    password:
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  liquibase:
    change-log: "classpath:dbchangelog.xml"


